version: "3.0"

services:
  postgres:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinyurl
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5431:5432"

  redis:
    container_name: redis
    image: redis/redis-stack
    expose:
      - "6379"
    ports:
      - "8001:8001"
      - "6379:6379"

  tinyurl:
    container_name: tinyurl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    links:
      - redis
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tinyurl
      SPRING_REDIS_HOST: redis
