spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/tinyurl
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

