spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5431/tinyurl
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

server:
  port: 8081
