spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5431}/${RDS_DB_NAME:tinyurl}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000
  compression:
    enabled: true
    mime-types: application/json
