name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@2.4.2
        with:
          arguments: clean build -x test

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: tinyurl
          environment_name: tinyurl-env
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: ./build/libs/application.jar
          wait_for_environment_recovery: 240